name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node + pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.4.1

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test

  docker:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: test

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract short SHA and set lowercase names
        id: vars
        run: |
          echo "sha_short=$(echo $GITHUB_SHA | cut -c1-8)" >> $GITHUB_ENV

          echo "repo_name=$(echo ${GITHUB_REPOSITORY##*/} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

          echo "owner_lower=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build \
            -t ghcr.io/${{ env.owner_lower }}/${{ env.repo_name }}:latest \
            -t ghcr.io/${{ env.owner_lower }}/${{ env.repo_name }}:${{ env.sha_short }} .

      - name: Push Docker image (latest + short-sha)
        run: |
          docker push ghcr.io/${{ env.owner_lower }}/${{ env.repo_name }}:latest
          docker push ghcr.io/${{ env.owner_lower }}/${{ env.repo_name }}:${{ env.sha_short }}

  deploy:
    name: Deploy with Docker Compose
    needs: docker
    runs-on: ubuntu-latest

    steps:
      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: SSH into server
        run: |
          sshpass -p ${{ secrets.SSH_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
          git clone https://github.com/JosafatJimenezB/Mini-devops-workshop.git
          cd Mini-devops-workshop/
          echo "Pulling latest changes from main branch"
          git pull origin main
          echo "Stopping and removing old containers"
          docker compose --profile prod down
          echo "Removing old images"
          docker image prune -f
          echo "Up new containers"
          docker compose --profile prod up -d
          EOF
